    # jobs:
    # - job: terraformInstall
    #   displayName: "Terraform Install and Init"
    #   steps:
    #     - task: TerraformInstaller@1
    #       inputs:
    #         terraformVersion: 'latest'
    #     - task: TerraformTask@5
    #       displayName: "Terraform Init"
    #       inputs:
    #         provider: 'azurerm'
    #         command: 'init'
    #         workingDirectory: '$(working_dir_dev)'
    #         backendServiceArm: 'azure_ado_sp'
    #         backendAzureRmOverrideSubscriptionID: '$(sub_id)'
    #         backendAzureRmResourceGroupName: '$(rg_name)'
    #         backendAzureRmStorageAccountName: '$(stg_name)'
    #         backendAzureRmContainerName: '$(blobcontainer_name)'
    #         backendAzureRmKey: '$(tfstate_Key)'

    #     - task: TerraformTask@5
    #       displayName: "Terraform fmt"
    #       inputs:
    #         provider: 'azurerm'
    #         command: 'custom'
    #         workingDirectory: '$(working_dir_dev)'
    #         commandOptions: 'fmt'
    #         outputTo: 'console'
    #         environmentServiceNameAzureRM: 'azure_ado_sp'




parameters:
  - name: workingDirectory          
    type: string

  - name: backendServiceArm         
    type: string

  - name: backendRgName             
    type: string

  - name: backendStorageAccount     
    type: string

  - name: backendContainerName      
    type: string

  # - name: SubscriptionID
  #   type: string

  - name: backendKey                
    type: string

  # - name: terraformVersion          
  #   type: string
  #   default: '1.14.2'

jobs:
- job: terraformInstall
  displayName: "Terraform Install and Init"
  steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: ${{ parameters.workingDirectory }}
        backendServiceArm: ${{ parameters.backendServiceArm }}
        #backendAzureRmOverrideSubscriptionID: ${{ parameters.SubscriptionID }}
        backendAzureRmResourceGroupName: ${{ parameters.backendRgName }}
        backendAzureRmStorageAccountName: ${{ parameters.backendStorageAccount }}
        backendAzureRmContainerName: ${{ parameters.backendContainerName }}
        backendAzureRmKey: ${{ parameters.backendKey }}


    - task: TerraformTask@5
      displayName: "Terraform fmt"
      inputs:
        provider: 'azurerm'
        command: 'custom'
        workingDirectory: ${{ parameters.workingDirectory }}
        customCommand: 'fmt'
        environmentServiceNameAzureRM: ${{ parameters.backendServiceArm }}

