jobs:
- job: terraformScanning
  displayName: "Infrastructure as Code Security Scanning"
  steps:

    - script: |
        echo "Installing IaC Security Tools..."
        arch -arm64 brew install tfsec
        arch -arm64 brew install checkov
        arch -arm64 brew install tflint
        arch -arm64 brew install terrascan
        arch -arm64 brew install aquasecurity/trivy/trivy
      displayName: "Install Scanners"

    - task: tfsec@1
      displayName: "TFSEC Scan"
      inputs:
        version: 'v1.26.0'
        dir: $(tf_working_dir)

    - script: |
        cd '$(tf_working_dir)'
        tflint --init
        tflint
      displayName: "TFLint Scan"

    - script: |
          echo "Running Checkov Scan..."
          checkov -d $(tf_working_dir)
        displayName: "Checkov Scan"   

    - script: |
        echo "Running Terrascan..."
        terrascan scan -i terraform -d $(tf_working_dir)
      displayName: "Terrascan Scan"

    - script: trivy config '$(tf_working_dir)'
      displayName: "Trivy Scan"
