parameters:
  - name: workingDirectory          
    type: string

  - name: backendServiceArm         
    type: string

  - name: backendRgName             
    type: string

  - name: backendStorageAccount     
    type: string

  - name: backendContainerName      
    type: string

  - name: backendKey                
    type: string


jobs:
- job: terraformPlan
  displayName: "Terraform Plan"
  steps:

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: ${{ parameters.workingDirectory }}
        backendServiceArm: ${{ parameters.backendServiceArm }}
        backendAzureRmResourceGroupName: ${{ parameters.backendRgName }}
        backendAzureRmStorageAccountName: ${{ parameters.backendStorageAccount }}
        backendAzureRmContainerName: ${{ parameters.backendContainerName }}
        backendAzureRmKey: ${{ parameters.backendKey }}

    - task: TerraformTask@5
      displayName: "Terraform Validate"
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: ${{ parameters.workingDirectory }}

    - task: TerraformTask@5
      displayName: "Terraform Plan"
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: ${{ parameters.workingDirectory }}
        environmentServiceNameAzureRM: ${{ parameters.backendServiceArm }}