jobs:
- job: destroyJob
  dependsOn: approvalJob
  condition: and(succeeded('approvalJob'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: "Terraform Destroy"
  steps:
    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(working_dir_dev)
        backendServiceArm: $(sc_name)
        backendAzureRmResourceGroupName: $(rg_name)
        backendAzureRmStorageAccountName: $(stg_name)
        backendAzureRmContainerName: $(blobcontainer_name)
        backendAzureRmKey: $(tfstate_Key)


    - task: TerraformTask@5
      displayName: Destroy
      inputs:
        provider: azurerm
        command: destroy
        workingDirectory: $(working_dir_dev)
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: $(sc_name)
