parameters:
  - name: workingDirectory          
    type: string

  - name: backendServiceArm         
    type: string

  - name: backendRgName             
    type: string

  - name: backendStorageAccount     
    type: string

  - name: backendContainerName      
    type: string

  - name: backendKey                
    type: string


jobs:
- job: terraformApply
  displayName: "Terraform Apply"
  steps:
    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: ${{ parameters.workingDirectory }}
        backendServiceArm: ${{ parameters.backendServiceArm }}
        backendAzureRmResourceGroupName: ${{ parameters.backendRgName }}
        backendAzureRmStorageAccountName: ${{ parameters.backendStorageAccount }}
        backendAzureRmContainerName: ${{ parameters.backendContainerName }}
        backendAzureRmKey: ${{ parameters.backendKey }}


    - task: TerraformTask@5
      displayName: Apply
      inputs:
        provider: azurerm
        command: apply
        workingDirectory: ${{ parameters.workingDirectory }}
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: ${{ parameters.backendServiceArm }}
